import 'bootstrap/dist/css/bootstrap.min.css';
import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="header">
      {<h2>NAVBAR </h2>}
    </div>
    
    
    <div className="container">




<div className="main-content">

  {/* Sección 1 */}
  <div className="row justify-content-center">
    <div className="col-12 col-md-8 mb-4">
      <div className="banner p-4 border bg-light rounded">
        <h2 className="text-center">SLIDER</h2>
      </div>
    </div>
  </div>

  {/* Sección 2 */}
  <div className="row justify-content-center">
    <div className="col-12 col-md-8 mb-4">
      <div className="banner p-4 border bg-light rounded">
        <h2 className="text-center">PROMOCIONES DESCUENTOS</h2>
      </div>
    </div>
  </div>

  {/* Sección 3 */}
  <div className="row justify-content-center">
    <div className="col-12 col-md-8 mb-4">
      <div className="features p-4 border bg-light rounded">
        <h2 className="text-center">SLIDER - Compra por categorías</h2>
      </div>
    </div>
  </div>

  {/* Sección 4 */}
  <div className="row justify-content-center">
    <div className="col-12 col-md-8 mb-4">
      <div className="testimonials p-4 border bg-light rounded">
        <h2 className="text-center">Las Mejores Promociones</h2>
      </div>
    </div>
  </div>

  {/* Sección 5 */}
  <div className="row justify-content-center">
    <div className="col-12 col-md-8 mb-4">
      <div className="testimonials p-4 border bg-light rounded">
        <h2 className="text-center">Días de Iluminación</h2>
      </div>
    </div>
  </div>

  {/* Sección 6 */}
  <div className="row justify-content-center">
    <div className="col-12 col-md-8 mb-4">
      <div className="testimonials p-4 border bg-light rounded">
        <h2 className="text-center">Descubre lo que menos esperas</h2>
      </div>
    </div>
  </div>

  {/* Sección 7 */}
  <div className="row justify-content-center">
    <div className="col-12 col-md-8 mb-4">
      <div className="testimonials p-4 border bg-light rounded">
        <h2 className="text-center">SLIDER COMPRAS RÁPIDAS</h2>
      </div>
    </div>
  </div>

  {/* Sección 8 */}
  <div className="row justify-content-center">
    <div className="col-12 col-md-8 mb-4">
      <div className="testimonials p-4 border bg-light rounded">
        <h2 className="text-center">Juntos logramos más</h2>
      </div>
    </div>
  </div>

  {/* Sección 9 */}
  <div className="row justify-content-center">
    <div className="col-12 col-md-8 mb-4">
      <div className="testimonials p-4 border bg-light rounded">
        <h2 className="text-center">Juntos hacemos tu proyecto</h2>
      </div>
    </div>
  </div>

  {/* Sección 10 */}
  <div className="row justify-content-center">
    <div className="col-12 col-md-8 mb-4">
      <div className="testimonials p-4 border bg-light rounded">
        <h2 className="text-center">Métodos de pago</h2>
      </div>
    </div>
  </div>

  {/* Sección 11 */}
  <div className="row justify-content-center">
    <div className="col-12 col-md-8 mb-4">
      <div className="testimonials p-4 border bg-light rounded">
        <h2 className="text-center">Especiales para ti</h2>
      </div>
    </div>
  </div>

</div>
</div>
    
    </>
  );
}
